# Generated by Django 5.1.1 on 2024-09-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
