# Generated by Django 5.1.1 on 2024-09-06 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('important', models.FloatField()),
                ('isDone', models.BooleanField(default=False)),
                ('layout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='conn.layout')),
            ],
        ),
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isStart', models.BooleanField(default=False)),
                ('isFinish', models.BooleanField(null=True)),
                ('finishTask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finish', to='conn.task')),
                ('startTask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start', to='conn.task', verbose_name='start')),
            ],
        ),
    ]
