# Generated by Django 5.1.1 on 2024-09-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conn', '0001_initial'),
        ('users', '0006_profile_about_profile_speciality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='connections',
            new_name='previous_connections',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='important',
            new_name='weight',
        ),
        migrations.RemoveField(
            model_name='task',
            name='borderColor',
        ),
        migrations.RemoveField(
            model_name='task',
            name='color',
        ),
        migrations.RemoveField(
            model_name='task',
            name='layout',
        ),
        migrations.RemoveField(
            model_name='task',
            name='textColor',
        ),
        migrations.RemoveField(
            model_name='task',
            name='toGoal',
        ),
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='requirement_skills',
            field=models.TextField(default='No special skills'),
        ),
        migrations.AddField(
            model_name='task',
            name='started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='workers',
            field=models.ManyToManyField(null=True, to='users.profile'),
        ),
        migrations.DeleteModel(
            name='Connector',
        ),
    ]
