# Generated by Django 5.1.1 on 2024-09-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conn', '0002_alter_connector_isfinish'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='connections',
            field=models.ManyToManyField(blank=True, related_name='related_tasks', to='conn.task'),
        ),
    ]
