# Generated by Django 5.1.1 on 2024-09-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conn', '0003_task_connections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connector',
            name='isStart',
        ),
        migrations.AddField(
            model_name='task',
            name='isStart',
            field=models.BooleanField(default=False),
        ),
    ]
