# Generated by Django 5.1.1 on 2024-09-07 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conn', '0004_remove_connector_isstart_task_isstart'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='toGoal',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
