# Generated by Django 5.1.1 on 2024-09-07 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conn', '0005_task_togoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='isFinish',
            field=models.BooleanField(default=False),
        ),
    ]
