# Generated by Django 5.1.1 on 2024-09-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conn', '0006_task_isfinish'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='color',
            field=models.CharField(default='green', max_length=255),
        ),
    ]
