# Generated by Django 5.1.1 on 2024-09-07 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conn', '0007_task_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='layout',
        ),
        migrations.AddField(
            model_name='task',
            name='layout',
            field=models.ManyToManyField(null=True, to='conn.layout'),
        ),
    ]
